### ISSUE TITLE
Error on import

### ISSUE THREAD

**Issue by fstakem** [Schiphol-Hub/ssim#5]
Probably missing 'install_requires' in setup.py:

Python 3.6.5 (default, Dec 26 2018, 13:41:35) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import ssim
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-d9d9dfb1bea8> in <module>
----> 1 import ssim

***/ssim_parser/sim_env/lib/python3.6/site-packages/ssim/__init__.py in <module>
----> 1 from .ssim import read, expand_slots

***/ssim_parser/sim_env/lib/python3.6/site-packages/ssim/ssim.py in <module>
      8 import re
      9 from datetime import datetime, timedelta, date
---> 10 from dateutil.rrule import rrule, WEEKLY
     11 import sys
     12 import os

ModuleNotFoundError: No module named 'dateutil'

**Comment by schaikr** [comment]
Hi there, we thought dateutil was standard library, but apparently, that's not the case. I'll fix it. Thanks for reporting!

**Comment by schaikr** [comment]
Fixed in 34978b9
